//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.EFDataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Code
    {
        public string UniqueId { get; set; }
        public string CodeText { get; set; }
        public string CodeValue { get; set; }
        public string ParentUniqueId { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUser { get; set; }
    }
}
