//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.EFDataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Attachment
    {
        public string UniqueId { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string Type { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUser { get; set; }
        public string FileExtension { get; set; }
    }
}
