//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.EFDataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_UserRoleOperationFunction
    {
        public string FunctionId { get; set; }
        public string FunctionName { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string OperationId { get; set; }
        public string OperationName { get; set; }
        public System.Guid RoleUniqueId { get; set; }
        public System.Guid UserUniqueId { get; set; }
    }
}
