//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.EFDataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow_Chart
    {
        public System.Guid UniqueId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string FlowChartContent { get; set; }
    }
}
