//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.EFDataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow_ReginsterUser
    {
        public System.Guid UniqueId { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<System.Guid> SupervisorAudit { get; set; }
        public Nullable<System.DateTime> SupervisorAuditTime { get; set; }
        public Nullable<System.Guid> SupervisorReview { get; set; }
        public Nullable<System.DateTime> SupervisorReviewTime { get; set; }
        public Nullable<System.Guid> FinalAudit { get; set; }
        public Nullable<System.DateTime> FinalAuditTime { get; set; }
        public Nullable<System.Guid> WorkFlowInstanceUniqueId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
